from datetime import *
time = datetime.now()
print(time)
print("----------------------------")
print("%a: "+time.strftime("%a"))
print("----------------------------")
print("%A: "+time.strftime("%A"))
print("----------------------------")
print("%b: "+time.strftime("%b"))
print("----------------------------")
print("%B: "+time.strftime("%B"))
print("----------------------------")
print("%w: "+time.strftime("%w"))
print("----------------------------")
print("%W: "+time.strftime("%W"))
print("----------------------------")
print("%z: "+time.strftime("%z"))
print("----------------------------")
print("%Z: "+time.strftime("%Z"))
print("----------------------------")
print("%y: "+time.strftime("%y"))
print("----------------------------")
print("%Y: "+time.strftime("%Y"))
print("----------------------------")
print("%m: "+time.strftime("%m"))
print("----------------------------")
print("%M: "+time.strftime("%M"))
print("----------------------------")
print("%x: "+time.strftime("%x"))
print("----------------------------")
print("%X: "+time.strftime("%X"))
print("----------------------------")
print("%c: "+time.strftime("%c"))
print("----------------------------")
print("%C: "+time.strftime("%C"))
print("----------------------------")
print("%p: "+time.strftime("%p"))
print("----------------------------")
print("%S: "+time.strftime("%S"))
print("----------------------------")
print("%d: "+time.strftime("%d"))
print("----------------------------")
print("%H: "+time.strftime("%H"))
print("----------------------------")
print("%I: "+time.strftime("%I"))
print("----------------------------")
print("%f: "+time.strftime("%f"))
print("----------------------------")
print("%%: "+time.strftime("%%"))
print("----------------------------")
print("%j: "+time.strftime("%j"))
print("----------------------------")
print("%u: "+time.strftime("%u"))
print("----------------------------")
print("%U: "+time.strftime("%U"))
print("----------------------------")
print("%G: "+time.strftime("%G"))
print("----------------------------")